Update yml_check.yaml

diff --git a/code_quality/yml_check.yaml b/code_quality/yml_check.yaml
--- a/code_quality/yml_check.yaml
+++ b/code_quality/yml_check.yaml
@@ -2,20 +2,15 @@ parameters:
   - name: SEARCH_PATH
     type: string
     default: '.'
-
 steps:
-  - task: PowerShell@2
-    displayName: "YML files checking"
-    inputs:
-      targetType: 'inline'
-      script: |
-        Write-Host "Searching for .yml files in '${{ parameters.SEARCH_PATH }}'"
-        $files = Get-ChildItem -Path '${{ parameters.SEARCH_PATH }}' -Recurse -Include *.yml
-        if ($files) {
-          Write-Error "Error: .yml files found in the repository:"
-          $files | ForEach-Object { Write-Error $_.FullName }
-          exit 1
-        }
-        else {
-          Write-Host "No .yml files found."
-        }
+  - script: |
+      echo "Searching for .yml files in ${{ parameters.SEARCH_PATH }}"
+      yml_files=$(find ${{ parameters.SEARCH_PATH }} -type f -name "*.yml")
+      if [ -n "$yml_files" ]; then
+        echo "Error: .yml files found in the repository:"
+        echo "$yml_files"
+        exit 1
+      else
+        echo "No .yml files found."
+      fi
+    displayName: "yml files checking"
